name: base
description: app base module
version: 0.0.7
author: cheng
homepage: ''

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.1 #flutter 中的数据库，可以在Android和iOS中同时使用
  #网络请求
  dio: ^3.0.9
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.1
  connectivity: '>=0.4.9 <2.0.0'

  path_provider: ^1.6.11 #抹平android和ios平台 文件路径的差异化
  shared_preferences: ^0.5.8 #本地轻量化数据存储  类似 Android中的SP
  device_info: ^0.4.2+2 #设备信息
  oktoast: ^2.3.2 # 全局Toast
  provider: ^4.3.2+1 #状态管理
  permission_handler: ^5.0.1+1  #动态权限申请
  #图片和视频相关
  photo_manager: ^0.5.8 #从本地图库选择多图(基础api类)
  #图片编辑，展示,网络图片缓存等等
  extended_image: ^1.1.0
  #图片编辑，原生库
  image_editor: ^0.7.1
  flutter_ffmpeg: ^0.2.10 #ffmpeg命令
  video_player: '>=0.10.12 <2.0.0'


  #上拉加载和下拉刷新
  flutter_easyrefresh: ^2.1.5
  #轮播图
  flutter_swiper: ^1.1.6
  camera:
    git:
      url: https://github.com/chengbook/camera.git
  jmessage_flutter:
    git:
      url: https://github.com/chengbook/jmessage.git
  pay:
    git:
      url: https://github.com/chengbook/pay.git



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
#  plugin:
#    platforms:
      # This plugin project was generated without specifying any
      # platforms with the `--platform` argument. If you see the `fake_platform` map below, remove it and
      # then add platforms following the instruction here:
      # https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms
      # -------------------
#      some_platform:
#        pluginClass: somePluginClass
    # -------------------

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/common_imgs/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
